version: '3.8'

services:
  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - cache
    environment:
      - REDIS_HOST=cache
    networks:
      - app-net
  cache:
    image: redis:7-alpine
    container_name: cache
    networks:
      - app-net

networks:
  app-net:
    driver: bridge