services:
  app:
    build: ./app
    environment:
      - REDIS_HOST=cache
    depends_on:
      cache:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks: [app-net]

  cache:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks: [app-net]

networks:
  app-net:
    driver: bridge
